name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Black-Formater:
    runs-on: ubuntu-latest
    steps:
      - name: Run python black code formatter
        uses: DataDog/action-py-black-formatter@v2.5

